### ISSUE TITLE
still under development?

### ISSUE THREAD

**Issue by dpep** [pupeno/hmap#1]
Hey, I inadvertently developed something pretty similar to this library and then bumped into your gem/code when I went to publish.  It looks like this library hasn't been worked on in a while and is a subset of what I built, so would you be willing to let me take over the gem?

https://github.com/dpep/rb_hmap

Thanks,

-Daniel

**Comment by pupeno** [comment]
Yes, of course. What do you need me to do?

**Comment by dpep** [comment]
great, I very much appreciate your willingness!  I believe the command is
```
gem owner hmap -a <EMAIL>
```

https://guides.rubygems.org/command-reference/#gem-owner

**Comment by pupeno** [comment]
Oh, sorry for the delay in this. I had a hectic week. I will definitely do
it. Do you know if there's a way to do it without the gem command, maybe on
the website? I'd be able to do it much quickly then as I don't have a ruby
environment set up on my laptop.

**Comment by dpep** [comment]
unfortunately, i believe they removed the ui route.  it looks like you can also do it via curl, which could save you time setting up the ruby env.

https://guides.rubygems.org/rubygems-org-api/
```
# get your auth token
curl -u pupeno https://rubygems.org/api/v1/api_key.yaml

# add owner
curl -H 'Authorization:<AUTH_TOKEN>' \
      -F 'email=<EMAIL>' \
      https://rubygems.org/api/v1/gems/hmap/owners

# verify changes
curl https://rubygems.org/api/v1/gems/hmap/owners.json
```

**Comment by pupeno** [comment]
This is now done.

**Comment by dpep** [comment]
much appreciated!
